#!/usr/bin/env python3
"""Generate English markdown analysis reports for MACU runs.

Two modes:
  1. Single run   →  writes <run_dir>_analysis.md
       python scripts/generate_report.py runs/subset36_replan5
  2. Compare two  →  writes runs/replan_budget_comparison.md
       python scripts/generate_report.py --compare runs/subset36_replan5 runs/subset36_replan1

Reuses the analysis primitives in analyze_task.py / analyze_run.py so the
reports stay consistent with the CLI tools (failure classification, node
taxonomy, replan-effect classification).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyze_task import node_taxonomy, replan_effects  # noqa: E402
from analyze_run import collect  # noqa: E402


def _config_line(run_dir: Path) -> str:
    m = re.search(r"replan(\d+)", run_dir.name)
    budget = m.group(1) if m else "?"
    return (f"manager=claude-opus-4-6, CUA=gpt-5.4-mini, provider=apptainer, "
            f"max_replans={budget}, 36-task stratified OSWorld subset")


def _classify_failure(rec: dict, no_traj: int, executed: int, claims_fail: bool) -> str:
    sc = rec["score"]
    if isinstance(sc, (int, float)) and sc >= 1.0:
        return "success"
    if isinstance(sc, (int, float)) and 0 < sc < 1:
        return "partial"
    if executed == 0 and no_traj > 0:
        return "infra_fail"
    if claims_fail:
        return "agent_gaveup"
    return "false_success"


_FAIL_WORDS = ("unfortunately", "not been completed", "could not", "unable",
               "failed", "not possible", "does not exist", "no such")
_CAT_LABEL = {
    "success": "Success (score = 1.0)",
    "partial": "Partial (0 < score < 1)",
    "false_success": "False success (agent claims done, evaluator = 0)",
    "agent_gaveup": "Agent gave up (declared infeasible)",
    "infra_fail": "Infrastructure failure (no valid trajectory)",
}
_CAT_ORDER = ["success", "partial", "false_success", "agent_gaveup", "infra_fail"]


def _enrich(run_dir: Path, rec: dict) -> dict:
    """Add failure-classification fields by reading the task's final_results."""
    fr = json.load(open(run_dir / rec["task_id"] / "final_results.json"))
    sub = {k: v for k, v in (fr.get("subtask_results") or {}).items()
           if k != "final_aggregation"}
    no_traj = sum(1 for v in sub.values()
                  if "No response found" in (v.get("response") or ""))
    executed = len(sub) - no_traj
    resp = fr.get("final_response") or ""
    claims_fail = any(w in resp.lower() for w in _FAIL_WORDS)
    rec = dict(rec)
    rec["resp"] = " ".join(resp.split())[:90]
    rec["category"] = _classify_failure(rec, no_traj, executed, claims_fail)
    rec["no_traj"] = no_traj
    return rec


def single_report(run_dir: Path) -> str:
    recs = [r for r in collect(run_dir) if r["state"] == "done"]
    recs = [_enrich(run_dir, r) for r in recs]
    scored = [r for r in recs if isinstance(r["score"], (int, float))]
    succ = sum(1 for r in scored if r["score"] >= 1.0)
    n = len(recs)

    L = [f"# MACU Run Analysis — {run_dir.name}\n",
         f"- **Run dir:** `{run_dir}/`",
         f"- **Config:** {_config_line(run_dir)}",
         f"- **Generated by:** `scripts/generate_report.py`\n"]

    # 1. Overall
    L.append("## 1. Overall\n")
    L.append("| Metric | Value |")
    L.append("|---|---|")
    L.append(f"| Success rate (score ≥ 1.0) | **{succ}/{len(scored)} = {succ/len(scored)*100:.1f}%** |")
    L.append(f"| Partial-credit mean | {sum(r['score'] for r in scored)/len(scored)*100:.1f}% |")
    L.append(f"| Total cost | ${sum(r['cost'] or 0 for r in recs):.2f} "
             f"(mean ${sum(r['cost'] or 0 for r in recs)/n:.3f}/task) |")
    L.append(f"| Total wall-clock | {sum(r['duration'] or 0 for r in recs)/60:.0f} min "
             f"(mean {sum(r['duration'] or 0 for r in recs)/n:.0f}s/task) |")
    L.append(f"| Replans applied | {sum(r['replans_applied'] or 0 for r in recs)} "
             f"(mean {sum(r['replans_applied'] or 0 for r in recs)/n:.1f}/task) |\n")

    # 2. Per-domain
    bydom = defaultdict(list)
    for r in scored:
        bydom[r["domain"]].append(r)
    L.append("## 2. Per-domain success rate\n")
    L.append("| Domain | SR | Mean cost | Mean wall-clock | Mean replan |")
    L.append("|---|---|---|---|---|")
    for dom in sorted(bydom):
        rs = bydom[dom]
        ok = sum(1 for r in rs if r["score"] >= 1.0)
        mc = sum(r["cost"] or 0 for r in rs) / len(rs)
        md = sum(r["duration"] or 0 for r in rs) / len(rs)
        mr = sum(r["replans_applied"] or 0 for r in rs) / len(rs)
        L.append(f"| {dom} | {ok}/{len(rs)} ({ok/len(rs)*100:.0f}%) | ${mc:.3f} | {md:.0f}s | {mr:.1f} |")

    # 3. Failure classification
    cat = Counter(r["category"] for r in recs)
    bycat = defaultdict(list)
    for r in recs:
        bycat[r["category"]].append(r)
    L.append("\n## 3. Outcome classification\n")
    L.append("| Category | Count | % |")
    L.append("|---|---|---|")
    for c in _CAT_ORDER:
        if cat[c]:
            L.append(f"| {_CAT_LABEL[c]} | {cat[c]} | {cat[c]/n*100:.0f}% |")
    for c in _CAT_ORDER:
        if not bycat[c]:
            continue
        L.append(f"\n### {_CAT_LABEL[c]} — {cat[c]}\n")
        L.append("| Domain | score | subtasks | no-traj | steps | replan | task_id | agent final response (excerpt) |")
        L.append("|---|---|---|---|---|---|---|---|")
        for r in sorted(bycat[c], key=lambda x: x["domain"]):
            sc = f"{r['score']:.2f}" if isinstance(r["score"], (int, float)) else str(r["score"])
            L.append(f"| {r['domain']} | {sc} | {r['n_subtasks']} | {r['no_traj']} | "
                     f"— | {r['replans_applied']} | `{r['task_id'][:13]}` | {r['resp'][:80]} |")

    # 4. Node dynamics
    si = sum(r.get("initial_cua") or 0 for r in recs)
    sa = sum(r.get("added_total") or 0 for r in recs)
    L.append("\n## 4. Graph dynamics\n")
    L.append("Nodes split into *initial* (planned in the first decomposition) vs "
             "*dynamically added* by replanning (retry / variant = alternative "
             "strategy / init_from = inherits a predecessor's VM state).\n")
    L.append("| | Count |")
    L.append("|---|---|")
    L.append(f"| Initial CUA subtasks | {si} (mean {si/n:.1f}/task) |")
    L.append(f"| Dynamically added | {sa} (mean {sa/n:.1f}/task) |")
    L.append(f"| ├─ retry | {sum(r.get('added_retry') or 0 for r in recs)} |")
    L.append(f"| ├─ init_from | {sum(r.get('added_init_from') or 0 for r in recs)} |")
    L.append(f"| └─ variant | {sum(r.get('added_variant') or 0 for r in recs)} |")
    grew = sum(1 for r in recs if (r.get("added_total") or 0) > 0)
    L.append(f"| Tasks that grew their graph | {grew}/{n} |")

    # 5. Replan effect
    rc = sum(r.get("replan_calls") or 0 for r in recs)
    rn = sum(r.get("replan_no_change") or 0 for r in recs)
    ri = sum(r.get("replan_instr_only") or 0 for r in recs)
    rs_ = sum(r.get("replan_structural") or 0 for r in recs)
    applied = ri + rs_
    L.append("\n## 5. Did replanning change graph structure?\n")
    L.append("A replan can be *applied* yet leave the topology unchanged (an "
             "instruction-only rewrite) vs *structural* (a node added/removed or "
             "an edge rewired).\n")
    L.append("| | Count |")
    L.append("|---|---|")
    L.append(f"| Replan calls | {rc} |")
    L.append(f"| ├─ no change (graph confirmed as-is) | {rn} ({rn/rc*100:.0f}%) |")
    L.append(f"| └─ applied | {applied} ({applied/rc*100:.0f}%) |")
    L.append(f"| &nbsp;&nbsp;├─ instruction-only (topology unchanged) | {ri} |")
    L.append(f"| &nbsp;&nbsp;└─ **structural** (nodes/edges changed) | **{rs_}** |")
    tstruct = sum(1 for r in recs if (r.get("replan_structural") or 0) > 0)
    L.append(f"| Tasks with ≥1 structural replan | {tstruct}/{n} |")
    L.append("\n_Structural changes were cross-checked against consecutive "
             "snapshot node/edge diffs (ground truth)._\n")

    L.append("---\n")
    L.append(f"*Per-task viewers: `{run_dir}/<task_id>/analysis.html`; "
             f"summary CSV: `{run_dir}_summary.csv`.*")
    return "\n".join(L)


def compare_report(run_a: Path, run_b: Path) -> str:
    """run_a, run_b = (higher-budget, lower-budget) for nice column order."""
    def index(rd):
        return {r["task_id"]: _enrich(rd, r)
                for r in collect(rd) if r["state"] == "done"}
    A, B = index(run_a), index(run_b)
    na, nb = run_a.name, run_b.name

    def agg(idx, key, default=0):
        return sum((r.get(key) or default) for r in idx.values())

    def sr(idx):
        s = [r for r in idx.values() if isinstance(r["score"], (int, float))]
        return sum(1 for r in s if r["score"] >= 1.0), len(s)

    sa, ta = sr(A)
    sb, tb = sr(B)
    L = [f"# Replan-budget comparison: {na} vs {nb}\n",
         "Same 36-task subset, identical config except `--max-replans`. "
         "Generated by `scripts/generate_report.py --compare`.\n",
         "## Overall\n",
         f"| Metric | {na} | {nb} |",
         "|---|---|---|",
         f"| Success rate (score ≥ 1.0) | **{sa}/{ta} = {sa/ta*100:.1f}%** | **{sb}/{tb} = {sb/tb*100:.1f}%** |",
         f"| Total cost | ${agg(A,'cost'):.2f} | ${agg(B,'cost'):.2f} |",
         f"| Total wall-clock (min) | {agg(A,'duration')/60:.0f} | {agg(B,'duration')/60:.0f} |",
         f"| Replans applied | {agg(A,'replans_applied')} | {agg(B,'replans_applied')} |\n"]

    L.append("## Did replanning change graph structure?\n")
    L.append("*Applied* ≠ *changed topology*: an applied replan may only rewrite "
             "instruction text.\n")
    L.append(f"| | {na} | {nb} |")
    L.append("|---|---|---|")
    L.append(f"| Replan calls | {agg(A,'replan_calls')} | {agg(B,'replan_calls')} |")
    L.append(f"| no change (confirmed as-is) | {agg(A,'replan_no_change')} | {agg(B,'replan_no_change')} |")
    L.append(f"| applied | {agg(A,'replan_instr_only')+agg(A,'replan_structural')} | "
             f"{agg(B,'replan_instr_only')+agg(B,'replan_structural')} |")
    L.append(f"| ├─ instruction-only | {agg(A,'replan_instr_only')} | {agg(B,'replan_instr_only')} |")
    L.append(f"| └─ **structural** | **{agg(A,'replan_structural')}** | **{agg(B,'replan_structural')}** |")
    L.append("\n## Per-domain success rate\n")
    domsA = defaultdict(list); domsB = defaultdict(list)
    for r in A.values():
        if isinstance(r["score"], (int, float)): domsA[r["domain"]].append(r)
    for r in B.values():
        if isinstance(r["score"], (int, float)): domsB[r["domain"]].append(r)
    L.append(f"| Domain | {na} | {nb} |")
    L.append("|---|---|---|")
    for dom in sorted(set(domsA) | set(domsB)):
        a = domsA.get(dom, []); b = domsB.get(dom, [])
        oa = sum(1 for r in a if r["score"] >= 1.0)
        ob = sum(1 for r in b if r["score"] >= 1.0)
        L.append(f"| {dom} | {oa}/{len(a)} | {ob}/{len(b)} |")

    # task-level flips
    L.append("\n## Task-level flips\n")
    def won(idx, tid): r = idx.get(tid); return isinstance(r and r["score"], (int, float)) and r["score"] >= 1.0
    a_only = [t for t in A if won(A, t) and t in B and not won(B, t)]
    b_only = [t for t in B if won(B, t) and t in A and not won(A, t)]
    L.append(f"- **{na} succeeds but {nb} fails** ({len(a_only)}): "
             + ", ".join(f"`{A[t]['domain']}/{t[:8]}`" for t in a_only))
    L.append(f"- **{nb} succeeds but {na} fails** ({len(b_only)}): "
             + ", ".join(f"`{B[t]['domain']}/{t[:8]}`" for t in b_only))
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate English markdown run reports.")
    ap.add_argument("run_dir", nargs="?", help="Run dir for a single-run report")
    ap.add_argument("--compare", nargs=2, metavar=("HIGH", "LOW"),
                    help="Two run dirs (higher then lower budget) for a comparison")
    ap.add_argument("-o", "--output", help="Override output path")
    args = ap.parse_args()

    if args.compare:
        a, b = Path(args.compare[0]).resolve(), Path(args.compare[1]).resolve()
        out = Path(args.output) if args.output else a.parent / "replan_budget_comparison.md"
        out.write_text(compare_report(a, b), encoding="utf-8")
        print(f"wrote {out}")
    elif args.run_dir:
        rd = Path(args.run_dir).resolve()
        out = Path(args.output) if args.output else rd.parent / f"{rd.name}_analysis.md"
        out.write_text(single_report(rd), encoding="utf-8")
        print(f"wrote {out}")
    else:
        ap.error("provide a run_dir or --compare HIGH LOW")


if __name__ == "__main__":
    main()
